name: Run Fetch PR Data

on:
  workflow_dispatch:  

jobs:
  fetch-pr-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Custom Action to Fetch PR Data
        uses: ./github/actions/fetch-pr-data-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: sshreepadmavathi/action-demo  # 🔁 Replace with any repo you want
