name: Test Fetch PR Action

on:
  workflow_dispatch:

jobs:
  fetch-pr-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo (super important!)
        uses: actions/checkout@v4

      - name: Run the local custom action
        uses: ./.github/actions/fetch-pr-data-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: shreepadmavathi/code-review-analytics
