name: Test Fetch PR Data

on:
  workflow_dispatch:

jobs:
  fetch-pr-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run PR fetcher
        uses: ./github/actions/fetch-pr-data-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: sshreepadmavathi/action-demo
